#!/bin/bash
python test_round_predictions_other_rounds.py 0
echo 'Finished 0'
python test_round_predictions_other_rounds.py 1
echo 'Finished 1'
python test_round_predictions_other_rounds.py 2
echo 'Finished 2'
python test_round_predictions_other_rounds.py 3
echo 'Finished 3'
python test_round_predictions_other_rounds.py 4
echo 'Finished 4'
python test_round_predictions_other_rounds.py 5
echo 'Finished 5'
python test_round_predictions_other_rounds.py 6
echo 'Finished 6'
python test_round_predictions_other_rounds.py 7
echo 'Finished 7'
python test_round_predictions_other_rounds.py 8
echo 'Finished 8'
python test_round_predictions_other_rounds.py 9
echo 'Finished 9'
python test_round_predictions_other_rounds.py 10
echo 'Finished 10'
python test_round_predictions_other_rounds.py 11
echo 'Finished 11'
python test_round_predictions_other_rounds.py 12
echo 'Finished 12'
python test_round_predictions_other_rounds.py 13
echo 'Finished 13'
python test_round_predictions_other_rounds.py 14
echo 'Finished 14'
python test_round_predictions_other_rounds.py 15
echo 'Finished 15'
python test_round_predictions_other_rounds.py 16
echo 'Finished 16'
python test_round_predictions_other_rounds.py 17
echo 'Finished 17'
python test_round_predictions_other_rounds.py 18
echo 'Finished 18'
python test_round_predictions_other_rounds.py 19
echo 'Finished 19'
python test_round_predictions_other_rounds.py 20
echo 'Finished 20'
python test_round_predictions_other_rounds.py 21
echo 'Finished 21'
python test_round_predictions_other_rounds.py 22
echo 'Finished 22'
python test_round_predictions_other_rounds.py 23
echo 'Finished 23'
python test_round_predictions_other_rounds.py 24
echo 'Finished 24'
python test_round_predictions_other_rounds.py 25
echo 'Finished 25'
python test_round_predictions_other_rounds.py 26
echo 'Finished 26'
python test_round_predictions_other_rounds.py 27
echo 'Finished 27'
python test_round_predictions_other_rounds.py 28
echo 'Finished 28'
python test_round_predictions_other_rounds.py 29
echo 'Finished 29'
python test_round_predictions_other_rounds.py 30
echo 'Finished 30'
python test_round_predictions_other_rounds.py 31
echo 'Finished 31'
python test_round_predictions_other_rounds.py 32
echo 'Finished 32'
python test_round_predictions_other_rounds.py 33
echo 'Finished 33'
python test_round_predictions_other_rounds.py 34
echo 'Finished 34'
python test_round_predictions_other_rounds.py 35
echo 'Finished 35'
python test_round_predictions_other_rounds.py 36
echo 'Finished 36'
python test_round_predictions_other_rounds.py 37
echo 'Finished 37'
python test_round_predictions_other_rounds.py 38
echo 'Finished 38'
python test_round_predictions_other_rounds.py 39
echo 'Finished 39'
python test_round_predictions_other_rounds.py 40
echo 'Finished 40'
python test_round_predictions_other_rounds.py 41
echo 'Finished 41'
python test_round_predictions_other_rounds.py 42
echo 'Finished 42'
python test_round_predictions_other_rounds.py 43
echo 'Finished 43'
python test_round_predictions_other_rounds.py 44
echo 'Finished 44'
python test_round_predictions_other_rounds.py 45
echo 'Finished 45'
python test_round_predictions_other_rounds.py 46
echo 'Finished 46'
python test_round_predictions_other_rounds.py 47
echo 'Finished 47'
python test_round_predictions_other_rounds.py 48
echo 'Finished 48'
python test_round_predictions_other_rounds.py 49
echo 'Finished 49'
python test_round_predictions_other_rounds.py 50
echo 'Finished 50'
python test_round_predictions_other_rounds.py 51
echo 'Finished 51'
python test_round_predictions_other_rounds.py 52
echo 'Finished 52'
python test_round_predictions_other_rounds.py 53
echo 'Finished 53'
python test_round_predictions_other_rounds.py 54
echo 'Finished 54'
python test_round_predictions_other_rounds.py 55
echo 'Finished 55'
python test_round_predictions_other_rounds.py 56
echo 'Finished 56'
python test_round_predictions_other_rounds.py 57
echo 'Finished 57'
python test_round_predictions_other_rounds.py 58
echo 'Finished 58'
python test_round_predictions_other_rounds.py 59
echo 'Finished 59'
python test_round_predictions_other_rounds.py 60
echo 'Finished 60'
python test_round_predictions_other_rounds.py 61
echo 'Finished 61'
python test_round_predictions_other_rounds.py 62
echo 'Finished 62'
python test_round_predictions_other_rounds.py 63
echo 'Finished 63'
python test_round_predictions_other_rounds.py 64
echo 'Finished 64'
python test_round_predictions_other_rounds.py 65
echo 'Finished 65'
python test_round_predictions_other_rounds.py 66
echo 'Finished 66'
python test_round_predictions_other_rounds.py 67
echo 'Finished 67'
python test_round_predictions_other_rounds.py 68
echo 'Finished 68'
python test_round_predictions_other_rounds.py 69
echo 'Finished 69'
python test_round_predictions_other_rounds.py 70
echo 'Finished 70'
python test_round_predictions_other_rounds.py 71
echo 'Finished 71'
python test_round_predictions_other_rounds.py 72
echo 'Finished 72'
python test_round_predictions_other_rounds.py 73
echo 'Finished 73'
python test_round_predictions_other_rounds.py 74
echo 'Finished 74'
python test_round_predictions_other_rounds.py 75
echo 'Finished 75'
python test_round_predictions_other_rounds.py 76
echo 'Finished 76'
python test_round_predictions_other_rounds.py 77
echo 'Finished 77'
python test_round_predictions_other_rounds.py 78
echo 'Finished 78'
python test_round_predictions_other_rounds.py 79
echo 'Finished 79'
python test_round_predictions_other_rounds.py 80
echo 'Finished 80'
python test_round_predictions_other_rounds.py 81
echo 'Finished 81'
python test_round_predictions_other_rounds.py 82
echo 'Finished 82'
python test_round_predictions_other_rounds.py 83
echo 'Finished 83'
python test_round_predictions_other_rounds.py 84
echo 'Finished 84'
python test_round_predictions_other_rounds.py 85
echo 'Finished 85'
python test_round_predictions_other_rounds.py 86
echo 'Finished 86'
python test_round_predictions_other_rounds.py 87
echo 'Finished 87'
python test_round_predictions_other_rounds.py 88
echo 'Finished 88'
python test_round_predictions_other_rounds.py 89
echo 'Finished 89'
python test_round_predictions_other_rounds.py 90
echo 'Finished 90'
python test_round_predictions_other_rounds.py 91
echo 'Finished 91'
python test_round_predictions_other_rounds.py 92
echo 'Finished 92'
python test_round_predictions_other_rounds.py 93
echo 'Finished 93'
python test_round_predictions_other_rounds.py 94
echo 'Finished 94'
python test_round_predictions_other_rounds.py 95
echo 'Finished 95'
python test_round_predictions_other_rounds.py 96
echo 'Finished 96'
python test_round_predictions_other_rounds.py 97
echo 'Finished 97'
python test_round_predictions_other_rounds.py 98
echo 'Finished 98'
python test_round_predictions_other_rounds.py 99
echo 'Finished 99'
python test_round_predictions_other_rounds.py 100
echo 'Finished 100'
python test_round_predictions_other_rounds.py 101
echo 'Finished 101'
python test_round_predictions_other_rounds.py 102
echo 'Finished 102'
python test_round_predictions_other_rounds.py 103
echo 'Finished 103'
python test_round_predictions_other_rounds.py 104
echo 'Finished 104'
python test_round_predictions_other_rounds.py 105
echo 'Finished 105'
python test_round_predictions_other_rounds.py 106
echo 'Finished 106'
python test_round_predictions_other_rounds.py 107
echo 'Finished 107'
python test_round_predictions_other_rounds.py 108
echo 'Finished 108'
python test_round_predictions_other_rounds.py 109
echo 'Finished 109'
python test_round_predictions_other_rounds.py 110
echo 'Finished 110'
python test_round_predictions_other_rounds.py 111
echo 'Finished 111'
python test_round_predictions_other_rounds.py 112
echo 'Finished 112'
python test_round_predictions_other_rounds.py 113
echo 'Finished 113'
python test_round_predictions_other_rounds.py 114
echo 'Finished 114'
python test_round_predictions_other_rounds.py 115
echo 'Finished 115'
python test_round_predictions_other_rounds.py 116
echo 'Finished 116'
python test_round_predictions_other_rounds.py 117
echo 'Finished 117'
python test_round_predictions_other_rounds.py 118
echo 'Finished 118'
python test_round_predictions_other_rounds.py 119
echo 'Finished 119'
python test_round_predictions_other_rounds.py 120
echo 'Finished 120'
